### ISSUE TITLE
bug: Arrive-by search generates wrong compressed query

### ISSUE THREAD

**Issue by monopoint** [AtB-AS/atb-bff#127]
## Observation
when doing a arrive-by search, clicking details will in most cases generate 404 for the single trip query, a warning message and no updates.

## Analysis
The BFF generates a `compressedQuery` which is added to all `Trips` from `tripSearch`. we use this compressed query to be able to find the specific Trip later, to get more details for it and to get updates for it (and later let users share the query)
the function `generateCompressedQuery()` compresses the raw `TripsSearch query`, only amending it with the `when` field from the `aimedStartTime` from the desired Journey. This will generate a query that does not work as intended when the raw query has `arriveBy: true` and or in some pages when it has a `pageCursor`.
The compressedQuery can not contain these fields in order to work properly.

## Implementation
set `arriveBy: false` and remove `cursor` from the compressed query.

**Comment by tormoseng** [comment]
Testet OK
